import {
  UserProfile,
  Study,
  ResearchSite,
  Participant,
  ScheduledVisit,
  MonitoringVisit,
  MonitoringFinding,
  ProtocolDeviation,
  DataQuery,
  SafetyCase,
  EthicsSubmission,
  InformedConsentRecord,
  AuditLogEntry,
  AppNotification
} from '@/types';
import { syncComputeSimpleHash } from './crypto';

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'user-pi-01',
    name: 'Dr. Sujata Sharma',
    email: 'dr.sharma@aiia.gov.in',
    role: 'pi',
    title: 'Professor & Head of Dravyaguna',
    institution: 'All India Institute of Ayurveda, New Delhi',
    department: 'Department of Clinical Research & Dravyaguna',
    assignedStudyIds: ['study-001', 'study-003', 'study-007'],
    assignedSiteIds: ['site-01', 'site-02']
  },
  {
    id: 'user-coord-01',
    name: 'Rajesh Kumar',
    email: 'rajesh.crc@aiia.gov.in',
    role: 'study_coordinator',
    title: 'Senior Clinical Research Coordinator',
    institution: 'AIIA New Delhi Clinical Research Unit',
    department: 'Clinical Trials Centre',
    assignedStudyIds: ['study-001', 'study-002', 'study-004'],
    assignedSiteIds: ['site-01']
  },
  {
    id: 'user-cra-01',
    name: 'Ananya Deshmukh',
    email: 'ananya.cra@aiia-monitoring.in',
    role: 'cra_monitor',
    title: 'Lead Clinical Research Associate',
    institution: 'National Clinical Monitoring Office',
    department: 'Quality Assurance & Site Monitoring',
    assignedStudyIds: ['study-001', 'study-002', 'study-003', 'study-004', 'study-005'],
    assignedSiteIds: ['site-01', 'site-02', 'site-03', 'site-04']
  },
  {
    id: 'user-iec-01',
    name: 'Prof. V. K. Joshi',
    email: 'iec.chair@aiia.gov.in',
    role: 'iec_member',
    title: 'Chairman, Institutional Ethics Committee',
    institution: 'All India Institute of Ayurveda',
    department: 'Institutional Ethics Board (Registered with CDSCO)',
    assignedStudyIds: ['study-001', 'study-002', 'study-003', 'study-004', 'study-005', 'study-006'],
    assignedSiteIds: []
  },
  {
    id: 'user-pv-01',
    name: 'Dr. Priya Nair',
    email: 'pv.officer@npvcc-ayush.gov.in',
    role: 'pharmacovigilance_officer',
    title: 'National Pharmacovigilance Program Coordinator',
    institution: 'National Pharmacovigilance Coordination Centre (NPvCC), AIIA',
    department: 'ASU&H Pharmacovigilance Division',
    assignedStudyIds: ['study-001', 'study-002', 'study-003', 'study-004', 'study-005', 'study-006', 'study-007', 'study-008', 'study-009', 'study-010'],
    assignedSiteIds: []
  },
  {
    id: 'user-admin-01',
    name: 'Vikramaditya Sen',
    email: 'admin.ctms@aiia.gov.in',
    role: 'admin',
    title: 'Chief Information Officer & CTMS Administrator',
    institution: 'All India Institute of Ayurveda',
    department: 'Research Informatics & Digital Health',
    assignedStudyIds: ['study-001', 'study-002', 'study-003', 'study-004', 'study-005', 'study-006', 'study-007', 'study-008', 'study-009', 'study-010'],
    assignedSiteIds: ['site-01', 'site-02', 'site-03', 'site-04', 'site-05', 'site-06']
  },
  {
    id: 'user-reg-01',
    name: 'S. K. Verma',
    email: 'regulator.audit@cdsco.nic.in',
    role: 'regulator',
    title: 'Inspector (Ayush Biologicals & CT)',
    institution: 'Central Drugs Standard Control Organisation / Ministry of Ayush',
    department: 'Regulatory Compliance & Clinical Audit Cell',
    assignedStudyIds: ['study-001', 'study-002', 'study-003'],
    assignedSiteIds: []
  }
];

export const MOCK_SITES: ResearchSite[] = [
  {
    id: 'site-01',
    code: 'AIIA-DEL',
    name: 'All India Institute of Ayurveda (AIIA) Apex Hospital',
    city: 'New Delhi',
    state: 'Delhi',
    principalInvestigator: 'Dr. Sujata Sharma',
    piPhone: '+91-11-29948491',
    status: 'active',
    recruitmentTarget: 180,
    enrolledCount: 162,
    lastMonitoringDate: '2026-08-15',
    nextMonitoringDate: '2026-10-10',
    openFindingsCount: 2,
    ethicsApprovalStatus: 'Approved'
  },
  {
    id: 'site-02',
    code: 'IPGTRA-JAM',
    name: 'Institute of Teaching & Research in Ayurveda (ITRA / IPGTRA)',
    city: 'Jamnagar',
    state: 'Gujarat',
    principalInvestigator: 'Prof. Mahesh Vyas',
    piPhone: '+91-288-2553936',
    status: 'active',
    recruitmentTarget: 120,
    enrolledCount: 104,
    lastMonitoringDate: '2026-07-28',
    nextMonitoringDate: '2026-10-25',
    openFindingsCount: 3,
    ethicsApprovalStatus: 'Approved'
  },
  {
    id: 'site-03',
    code: 'NIA-JAI',
    name: 'National Institute of Ayurveda (Deemed to be University)',
    city: 'Jaipur',
    state: 'Rajasthan',
    principalInvestigator: 'Prof. Sanjeev Sharma',
    piPhone: '+91-141-2635816',
    status: 'active',
    recruitmentTarget: 140,
    enrolledCount: 118,
    lastMonitoringDate: '2026-08-04',
    nextMonitoringDate: '2026-11-05',
    openFindingsCount: 1,
    ethicsApprovalStatus: 'Approved'
  },
  {
    id: 'site-04',
    code: 'BHU-VAR',
    name: 'Faculty of Ayurveda, IMS Banaras Hindu University',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    principalInvestigator: 'Dr. Anand Kumar Chaudhary',
    piPhone: '+91-542-2367500',
    status: 'active',
    recruitmentTarget: 110,
    enrolledCount: 88,
    lastMonitoringDate: '2026-06-20',
    nextMonitoringDate: '2026-09-30',
    openFindingsCount: 4,
    ethicsApprovalStatus: 'Approved'
  },
  {
    id: 'site-05',
    code: 'GAC-TVM',
    name: 'Government Ayurveda College Hospital',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    principalInvestigator: 'Dr. G. Anilkumar',
    piPhone: '+91-471-2460190',
    status: 'active',
    recruitmentTarget: 90,
    enrolledCount: 76,
    lastMonitoringDate: '2026-07-12',
    nextMonitoringDate: '2026-10-18',
    openFindingsCount: 0,
    ethicsApprovalStatus: 'Approved'
  },
  {
    id: 'site-06',
    code: 'RAP-MUM',
    name: 'R.A. Podar Ayurved Medical College & MA Podar Hospital',
    city: 'Mumbai',
    state: 'Maharashtra',
    principalInvestigator: 'Dr. Sampada Sant',
    piPhone: '+91-22-24934214',
    status: 'active',
    recruitmentTarget: 100,
    enrolledCount: 65,
    lastMonitoringDate: '2026-05-18',
    nextMonitoringDate: '2026-10-02',
    openFindingsCount: 5,
    ethicsApprovalStatus: 'Renewal Required'
  },
  {
    id: 'site-07',
    code: 'CCRAS-DEL',
    name: 'Central Council for Research in Ayurvedic Sciences HQ Site',
    city: 'New Delhi',
    state: 'Delhi',
    principalInvestigator: 'Dr. N. Srikanth',
    piPhone: '+91-11-28525852',
    status: 'active',
    recruitmentTarget: 80,
    enrolledCount: 72,
    lastMonitoringDate: '2026-08-20',
    nextMonitoringDate: '2026-11-15',
    openFindingsCount: 1,
    ethicsApprovalStatus: 'Approved'
  },
  {
    id: 'site-08',
    code: 'AIIMS-RIS',
    name: 'AIIMS-AIIA Centre for Integrative Medicine & Research',
    city: 'Rishikesh',
    state: 'Uttarakhand',
    principalInvestigator: 'Dr. Vandana Verma',
    piPhone: '+91-135-2462940',
    status: 'pending_activation',
    recruitmentTarget: 60,
    enrolledCount: 0,
    nextMonitoringDate: '2026-10-12',
    openFindingsCount: 2,
    ethicsApprovalStatus: 'Pending'
  }
];

export const MOCK_STUDIES: Study[] = [
  {
    id: 'study-001',
    code: 'AIIA-CT-2024-001',
    title: 'Multicentre Double-Blind RCT of Standardized Ashwagandha (Withania somnifera) Aqueous Extract in Generalized Anxiety Disorder',
    protocolNumber: 'AIIA/CLIN/2024/RCT-01',
    protocolVersion: 'v3.2',
    studyType: 'Interventional RCT',
    phase: 'Phase III',
    principalInvestigator: 'Dr. Sujata Sharma',
    piId: 'user-pi-01',
    sponsor: 'Ministry of Ayush / Central Council for Research in Ayurvedic Sciences',
    indication: 'Generalized Anxiety Disorder (Chittodvega / Manovaha Sroto Dusti)',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Aqueous Withania somnifera Extract 300mg bid (Withanolides > 5%)',
    comparatorProduct: 'Matched Inactive Starch Placebo Capsule bid',
    plannedTarget: 240,
    enrolledCount: 218,
    screenedCount: 310,
    completedCount: 145,
    startDate: '2024-06-01',
    endDate: '2026-12-31',
    status: 'recruiting',
    participatingSiteIds: ['site-01', 'site-02', 'site-03', 'site-04'],
    ctriNumber: 'CTRI/2024/05/067812',
    ctriStatus: 'Registered',
    ctriUrl: 'https://ctri.nic.in/Clinicaltrials/pmaindet2.php?trialid=67812',
    iecName: 'AIIA Institutional Ethics Committee for Clinical Studies',
    iecApprovalRef: 'AIIA/IEC/2024/PROT-089',
    iecApprovalDate: '2024-04-12',
    iecExpiryDate: '2027-04-11',
    iecStatus: 'Approved',
    documentsCount: 18,
    budgetAllocatedLakhs: 84.5,
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2026-09-20T14:30:00Z',
    assignedTeam: [
      { userId: 'user-pi-01', name: 'Dr. Sujata Sharma', role: 'pi' },
      { userId: 'user-coord-01', name: 'Rajesh Kumar', role: 'study_coordinator' },
      { userId: 'user-cra-01', name: 'Ananya Deshmukh', role: 'cra_monitor' }
    ],
    milestones: [
      { id: 'm-1', title: 'Protocol Draft v1.0 Finalized', category: 'protocol', plannedDate: '2024-02-28', actualDate: '2024-02-25', responsiblePerson: 'Dr. Sujata Sharma', status: 'completed' },
      { id: 'm-2', title: 'Institutional Ethics Committee Approval', category: 'ethics', plannedDate: '2024-04-15', actualDate: '2024-04-12', responsiblePerson: 'Prof. V. K. Joshi', status: 'completed' },
      { id: 'm-3', title: 'CTRI Prospective Registration', category: 'ctri', plannedDate: '2024-05-15', actualDate: '2024-05-08', responsiblePerson: 'Rajesh Kumar', status: 'completed', evidenceRef: 'CTRI/2024/05/067812' },
      { id: 'm-4', title: 'Site Initiation & Drug Accountability Sign-off', category: 'site_activation', plannedDate: '2024-05-30', actualDate: '2024-05-29', responsiblePerson: 'Ananya Deshmukh', status: 'completed' },
      { id: 'm-5', title: '50% Recruitment Milestone (120 Participants)', category: 'recruitment', plannedDate: '2025-05-30', actualDate: '2025-05-18', responsiblePerson: 'Dr. Sujata Sharma', status: 'completed' },
      { id: 'm-6', title: 'Full Recruitment Target (240 Participants)', category: 'recruitment', plannedDate: '2026-10-31', responsiblePerson: 'Dr. Sujata Sharma', status: 'in_progress' },
      { id: 'm-7', title: 'Interim DSMB Safety & Efficacy Review', category: 'data_lock', plannedDate: '2026-10-15', responsiblePerson: 'Dr. Priya Nair', status: 'pending' },
      { id: 'm-8', title: 'Database Lock & CDISC Package Generation', category: 'data_lock', plannedDate: '2027-01-30', responsiblePerson: 'Vikramaditya Sen', status: 'pending' }
    ]
  },
  {
    id: 'study-002',
    code: 'AIIA-CT-2024-002',
    title: 'Efficacy, Safety and Immunomodulatory Mechanism of AYUSH-64 in Upper Respiratory Viral Infections and Post-Infectious Asthenia',
    protocolNumber: 'AIIA/CLIN/2024/A64-02',
    protocolVersion: 'v2.1',
    studyType: 'Interventional RCT',
    phase: 'Phase III',
    principalInvestigator: 'Prof. Anand Chaudhary',
    piId: 'user-pi-02',
    sponsor: 'Central Council for Research in Ayurvedic Sciences (CCRAS)',
    indication: 'Acute Viral Rhinosinusitis & Sannipata Jwara Sequelae',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'AYUSH-64 Tablet (500mg, 2 tabs tid for 14 days)',
    comparatorProduct: 'Standard Standardized Symptomatic Care Control',
    plannedTarget: 300,
    enrolledCount: 295,
    screenedCount: 380,
    completedCount: 260,
    startDate: '2024-03-01',
    endDate: '2026-11-30',
    status: 'active',
    participatingSiteIds: ['site-01', 'site-04', 'site-05', 'site-07'],
    ctriNumber: 'CTRI/2024/02/064120',
    ctriStatus: 'Registered',
    ctriUrl: 'https://ctri.nic.in/Clinicaltrials/pmaindet2.php?trialid=64120',
    iecName: 'Central Ethics Committee, AIIA',
    iecApprovalRef: 'AIIA/CEC/2024/044',
    iecApprovalDate: '2024-01-20',
    iecExpiryDate: '2026-10-25',
    iecStatus: 'Approved',
    documentsCount: 24,
    budgetAllocatedLakhs: 112.0,
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2026-09-22T11:20:00Z',
    assignedTeam: [
      { userId: 'user-coord-01', name: 'Rajesh Kumar', role: 'study_coordinator' },
      { userId: 'user-cra-01', name: 'Ananya Deshmukh', role: 'cra_monitor' },
      { userId: 'user-pv-01', name: 'Dr. Priya Nair', role: 'pharmacovigilance_officer' }
    ],
    milestones: [
      { id: 'm-201', title: 'Protocol Approval & CTRI Listing', category: 'ctri', plannedDate: '2024-02-15', actualDate: '2024-02-10', responsiblePerson: 'Rajesh Kumar', status: 'completed' },
      { id: 'm-202', title: 'Recruitment Completion (300 Enrolled)', category: 'recruitment', plannedDate: '2026-09-30', responsiblePerson: 'Prof. Anand Chaudhary', status: 'in_progress' },
      { id: 'm-203', title: 'Continuing Ethics Review Renewal', category: 'ethics', plannedDate: '2026-10-15', responsiblePerson: 'Prof. V. K. Joshi', status: 'overdue', comments: 'Expiry date approaching on 25-Oct-2026' }
    ]
  },
  {
    id: 'study-003',
    code: 'AIIA-CT-2024-003',
    title: 'Nano-Formulation Haridra Extract (Curcuma longa) vs. Aceclofenac in Primary Knee Osteoarthritis (Sandhigatavata): Non-Inferiority RCT',
    protocolNumber: 'AIIA/CLIN/2024/HAR-03',
    protocolVersion: 'v1.4',
    studyType: 'Interventional RCT',
    phase: 'Phase III',
    principalInvestigator: 'Dr. Sujata Sharma',
    piId: 'user-pi-01',
    sponsor: 'AIIA Intramural Research Fund & Indian Council of Medical Research (ICMR)',
    indication: 'Primary Knee Osteoarthritis (Sandhigatavata)',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Bioenhanced Nano-Curcuminoid 250mg bid',
    comparatorProduct: 'Aceclofenac 100mg bid + Rabeprazole 20mg od',
    plannedTarget: 180,
    enrolledCount: 165,
    screenedCount: 220,
    completedCount: 98,
    startDate: '2024-09-01',
    endDate: '2027-03-31',
    status: 'recruiting',
    participatingSiteIds: ['site-01', 'site-03', 'site-06'],
    ctriNumber: 'CTRI/2024/08/071940',
    ctriStatus: 'Registered',
    iecName: 'AIIA Institutional Ethics Committee',
    iecApprovalRef: 'AIIA/IEC/2024/112',
    iecApprovalDate: '2024-07-15',
    iecExpiryDate: '2027-07-14',
    iecStatus: 'Approved',
    documentsCount: 14,
    budgetAllocatedLakhs: 72.8,
    createdAt: '2024-06-10T12:00:00Z',
    updatedAt: '2026-09-24T16:00:00Z',
    assignedTeam: [
      { userId: 'user-pi-01', name: 'Dr. Sujata Sharma', role: 'pi' },
      { userId: 'user-cra-01', name: 'Ananya Deshmukh', role: 'cra_monitor' }
    ],
    milestones: [
      { id: 'm-301', title: 'Site Activation at Mumbai & Jaipur', category: 'site_activation', plannedDate: '2024-09-15', actualDate: '2024-09-14', responsiblePerson: 'Ananya Deshmukh', status: 'completed' },
      { id: 'm-302', title: 'Patient Reported WOMAC Index Verification', category: 'protocol', plannedDate: '2026-08-30', actualDate: '2026-08-28', responsiblePerson: 'Dr. Sujata Sharma', status: 'completed' }
    ]
  },
  {
    id: 'study-004',
    code: 'AIIA-CT-2025-004',
    title: 'Guduchi Ghanvati and Amalaki Rasayana in Prediabetes (Apathyanimittaja Prameha) with Metformin: A Factorial Pragmatic Study',
    protocolNumber: 'AIIA/CLIN/2025/GUD-04',
    protocolVersion: 'v2.0',
    studyType: 'Pragmatic Clinical Trial',
    phase: 'Phase II',
    principalInvestigator: 'Prof. Sanjeev Sharma',
    piId: 'user-pi-03',
    sponsor: 'Ministry of Ayush Flagship Disease Program',
    indication: 'Impaired Fasting Glucose & Early Type 2 Diabetes',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Guduchi Ghanvati 1g bid + Amalaki Churna 3g bid',
    comparatorProduct: 'Standard Lifestyle Advice + Metformin 500mg where indicated',
    plannedTarget: 200,
    enrolledCount: 140,
    screenedCount: 210,
    completedCount: 52,
    startDate: '2025-01-15',
    endDate: '2027-06-30',
    status: 'recruiting',
    participatingSiteIds: ['site-01', 'site-02', 'site-03'],
    ctriNumber: 'CTRI/2025/01/078120',
    ctriStatus: 'Registered',
    iecName: 'Joint Ethics Committee AIIA-NIA',
    iecApprovalRef: 'NIA/IEC/2024/098',
    iecApprovalDate: '2024-11-20',
    iecExpiryDate: '2026-11-19',
    iecStatus: 'Approved',
    documentsCount: 11,
    budgetAllocatedLakhs: 65.0,
    createdAt: '2024-10-05T08:00:00Z',
    updatedAt: '2026-09-18T10:15:00Z',
    assignedTeam: [
      { userId: 'user-coord-01', name: 'Rajesh Kumar', role: 'study_coordinator' }
    ],
    milestones: [
      { id: 'm-401', title: 'Baseline HbA1c & Insulin Assay Standardization', category: 'protocol', plannedDate: '2025-01-20', actualDate: '2025-01-18', responsiblePerson: 'Prof. Sanjeev Sharma', status: 'completed' },
      { id: 'm-402', title: '6-Month Glycemic Monitoring Review', category: 'protocol', plannedDate: '2026-07-30', actualDate: '2026-07-25', responsiblePerson: 'Rajesh Kumar', status: 'completed' }
    ]
  },
  {
    id: 'study-005',
    code: 'AIIA-CT-2025-005',
    title: 'Standardized Brahmi (Bacopa monnieri) Extract in Age-Associated Cognitive Decline & Memory Impairment (Smritibhramsha)',
    protocolNumber: 'AIIA/CLIN/2025/BRA-05',
    protocolVersion: 'v1.1',
    studyType: 'Interventional RCT',
    phase: 'Phase II',
    principalInvestigator: 'Dr. G. Anilkumar',
    piId: 'user-pi-04',
    sponsor: 'National Medicinal Plants Board (NMPB)',
    indication: 'Mild Cognitive Impairment (MCI) in Geriatric Cohort',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Bacoside-standardized Bacopa monnieri extract 450mg od',
    comparatorProduct: 'Matched placebo capsule od',
    plannedTarget: 150,
    enrolledCount: 82,
    screenedCount: 135,
    completedCount: 30,
    startDate: '2025-04-01',
    endDate: '2027-09-30',
    status: 'recruiting',
    participatingSiteIds: ['site-01', 'site-05'],
    ctriNumber: 'CTRI/2025/03/081290',
    ctriStatus: 'Registered',
    iecName: 'AIIA Institutional Ethics Committee',
    iecApprovalRef: 'AIIA/IEC/2025/032',
    iecApprovalDate: '2025-02-14',
    iecExpiryDate: '2027-02-13',
    iecStatus: 'Approved',
    documentsCount: 9,
    budgetAllocatedLakhs: 58.0,
    createdAt: '2025-01-12T11:00:00Z',
    updatedAt: '2026-09-15T09:40:00Z',
    assignedTeam: [
      { userId: 'user-cra-01', name: 'Ananya Deshmukh', role: 'cra_monitor' }
    ],
    milestones: [
      { id: 'm-501', title: 'Neuropsychological Battery (HMSE & MoCA) Validation', category: 'protocol', plannedDate: '2025-04-10', actualDate: '2025-04-08', responsiblePerson: 'Dr. G. Anilkumar', status: 'completed' }
    ]
  },
  {
    id: 'study-006',
    code: 'AIIA-CT-2025-006',
    title: 'Punarnavadi Mandura vs Ferrous Ascorbate in Iron Deficiency Anemia (Garbhini Pandu) during Second Trimester of Pregnancy',
    protocolNumber: 'AIIA/CLIN/2025/PUN-06',
    protocolVersion: 'v1.0',
    studyType: 'Interventional RCT',
    phase: 'Phase IV / Post-Marketing',
    principalInvestigator: 'Dr. Sampada Sant',
    piId: 'user-pi-05',
    sponsor: 'Ayush Stree Roga Clinical Consortium',
    indication: 'Pregnancy-associated Nutritional Anemia',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Punarnavadi Mandura 500mg bid with Takra',
    comparatorProduct: 'Ferrous Ascorbate 100mg + Folic Acid 1.5mg od',
    plannedTarget: 160,
    enrolledCount: 110,
    screenedCount: 175,
    completedCount: 64,
    startDate: '2025-03-01',
    endDate: '2027-02-28',
    status: 'recruiting',
    participatingSiteIds: ['site-01', 'site-06'],
    ctriNumber: 'CTRI/2025/02/079540',
    ctriStatus: 'Registered',
    iecName: 'AIIA Institutional Ethics Committee',
    iecApprovalRef: 'AIIA/IEC/2025/019',
    iecApprovalDate: '2025-01-25',
    iecExpiryDate: '2027-01-24',
    iecStatus: 'Approved',
    documentsCount: 15,
    budgetAllocatedLakhs: 52.0,
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2026-09-21T15:00:00Z',
    assignedTeam: [
      { userId: 'user-pv-01', name: 'Dr. Priya Nair', role: 'pharmacovigilance_officer' }
    ],
    milestones: [
      { id: 'm-601', title: 'Heavy Metal Safety Testing Certification in Drug Lots', category: 'protocol', plannedDate: '2025-02-20', actualDate: '2025-02-18', responsiblePerson: 'Dr. Sampada Sant', status: 'completed', evidenceRef: 'NABL-LAB-REP-2025-88' }
    ]
  },
  {
    id: 'study-007',
    code: 'AIIA-CT-2026-007',
    title: 'Varunadi Kashaya and Pashanabheda Churna in Asymptomatic Nephrolithiasis (Ashmari): A Multicentre Dose-Optimized Phase II Trial',
    protocolNumber: 'AIIA/CLIN/2026/VAR-07',
    protocolVersion: 'v1.0',
    studyType: 'Interventional RCT',
    phase: 'Phase II',
    principalInvestigator: 'Dr. Sujata Sharma',
    piId: 'user-pi-01',
    sponsor: 'Department of Shalya Tantra & Dravyaguna, AIIA',
    indication: 'Renal Calculi < 8mm in diameter',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Varunadi Kashaya concentrated sachet 15ml bid',
    comparatorProduct: 'Potassium Magnesium Citrate syrup 15ml bid',
    plannedTarget: 120,
    enrolledCount: 0,
    screenedCount: 0,
    completedCount: 0,
    startDate: '2026-11-01',
    endDate: '2028-04-30',
    status: 'awaiting_ethics',
    participatingSiteIds: ['site-01', 'site-02'],
    ctriNumber: 'CTRI/PENDING/2026-07',
    ctriStatus: 'Not Submitted',
    iecName: 'AIIA Institutional Ethics Committee',
    iecApprovalRef: 'AIIA/IEC/SUB-2026-014',
    iecStatus: 'Under Review',
    documentsCount: 6,
    budgetAllocatedLakhs: 44.0,
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-09-25T11:00:00Z',
    assignedTeam: [
      { userId: 'user-pi-01', name: 'Dr. Sujata Sharma', role: 'pi' }
    ],
    milestones: [
      { id: 'm-701', title: 'Formal IEC Review Presentation', category: 'ethics', plannedDate: '2026-10-05', responsiblePerson: 'Prof. V. K. Joshi', status: 'pending' },
      { id: 'm-702', title: 'CTRI Prospective Filing Post-Ethics', category: 'ctri', plannedDate: '2026-10-20', responsiblePerson: 'Dr. Sujata Sharma', status: 'pending' }
    ]
  },
  {
    id: 'study-008',
    code: 'AIIA-CT-2026-008',
    title: 'National Pharmacovigilance Registry on Adverse Drug Reaction Profiles of Herbo-Mineral Classical Rasaushadhi Formulations',
    protocolNumber: 'NPVCC/REG/2026/RAS-08',
    protocolVersion: 'v2.0',
    studyType: 'Safety & Pharmacovigilance Registry',
    phase: 'Phase IV / Post-Marketing',
    principalInvestigator: 'Dr. Priya Nair',
    piId: 'user-pv-01',
    sponsor: 'National Pharmacovigilance Coordination Centre (NPvCC), Ministry of Ayush',
    indication: 'Active Pharmacovigilance Surveillance of Bhasmas and Kupipakwa Rasayana',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Surveillance of 12 Scheduled Rasaushadhi medicines',
    plannedTarget: 500,
    enrolledCount: 380,
    screenedCount: 420,
    completedCount: 290,
    startDate: '2024-01-01',
    endDate: '2028-12-31',
    status: 'active',
    participatingSiteIds: ['site-01', 'site-02', 'site-03', 'site-04', 'site-05', 'site-06', 'site-07'],
    ctriNumber: 'CTRI/2023/12/062890',
    ctriStatus: 'Registered',
    iecName: 'Central Ethics Committee for Pharmacovigilance Registries',
    iecApprovalRef: 'NPVCC/IEC/2023/001',
    iecApprovalDate: '2023-11-15',
    iecExpiryDate: '2028-11-14',
    iecStatus: 'Approved',
    documentsCount: 22,
    budgetAllocatedLakhs: 140.0,
    createdAt: '2023-10-15T09:00:00Z',
    updatedAt: '2026-09-28T10:00:00Z',
    assignedTeam: [
      { userId: 'user-pv-01', name: 'Dr. Priya Nair', role: 'pharmacovigilance_officer' },
      { userId: 'user-admin-01', name: 'Vikramaditya Sen', role: 'admin' }
    ],
    milestones: [
      { id: 'm-801', title: 'Periodic Signal Detection Report Q2 2026', category: 'reporting', plannedDate: '2026-07-15', actualDate: '2026-07-10', responsiblePerson: 'Dr. Priya Nair', status: 'completed' },
      { id: 'm-802', title: 'Annual Safety Update Report to CDSCO', category: 'reporting', plannedDate: '2026-11-30', responsiblePerson: 'Dr. Priya Nair', status: 'pending' }
    ]
  },
  {
    id: 'study-009',
    code: 'AIIA-CT-2026-009',
    title: 'Shatavari Ghritha in Perimenopausal Vasomotor Symptoms and Osteopenia: An Open-Label Comparative Effectiveness Study',
    protocolNumber: 'AIIA/CLIN/2026/SHA-09',
    protocolVersion: 'v1.0',
    studyType: 'Comparative Effectiveness',
    phase: 'Phase III',
    principalInvestigator: 'Dr. Sampada Sant',
    piId: 'user-pi-05',
    sponsor: 'AIIA Prasuti Tantra Research Division',
    indication: 'Menopausal Syndrome (Rajonavritti Lakshana)',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Shatavari Ghritha 10g bid with warm cow milk',
    comparatorProduct: 'Isoflavone dietary supplement 50mg od',
    plannedTarget: 140,
    enrolledCount: 15,
    screenedCount: 25,
    completedCount: 0,
    startDate: '2026-08-01',
    endDate: '2028-02-28',
    status: 'recruiting',
    participatingSiteIds: ['site-01', 'site-06'],
    ctriNumber: 'CTRI/2026/07/092140',
    ctriStatus: 'Registered',
    iecName: 'AIIA Institutional Ethics Committee',
    iecApprovalRef: 'AIIA/IEC/2026/078',
    iecApprovalDate: '2026-06-18',
    iecExpiryDate: '2028-06-17',
    iecStatus: 'Approved',
    documentsCount: 8,
    budgetAllocatedLakhs: 49.0,
    createdAt: '2026-05-10T11:00:00Z',
    updatedAt: '2026-09-26T14:00:00Z',
    assignedTeam: [
      { userId: 'user-coord-01', name: 'Rajesh Kumar', role: 'study_coordinator' }
    ],
    milestones: [
      { id: 'm-901', title: 'Site Initiation Visit at Podar Hospital Mumbai', category: 'site_activation', plannedDate: '2026-08-10', actualDate: '2026-08-05', responsiblePerson: 'Ananya Deshmukh', status: 'completed' }
    ]
  },
  {
    id: 'study-010',
    code: 'AIIA-CT-2023-010',
    title: 'Purified Bhallataka (Semecarpus anacardium) Kshira Paka in Chronic Rheumatoid Arthritis (Amavata): A Phase I/II Dose-Escalation Safety Study',
    protocolNumber: 'AIIA/CLIN/2023/BHA-10',
    protocolVersion: 'v3.0',
    studyType: 'Interventional RCT',
    phase: 'Phase I',
    principalInvestigator: 'Dr. Sujata Sharma',
    piId: 'user-pi-01',
    sponsor: 'AIIA Apex Clinical Research Grants',
    indication: 'Severe Active Rheumatoid Arthritis refractory to first-line disease modifiers',
    ayushSystem: 'Ayurveda',
    investigationalProduct: 'Shodhita Bhallataka Kshira Paka (Graduated drops 1 to 10 drops)',
    plannedTarget: 60,
    enrolledCount: 60,
    screenedCount: 85,
    completedCount: 58,
    startDate: '2023-05-01',
    endDate: '2025-11-30',
    status: 'completed',
    participatingSiteIds: ['site-01'],
    ctriNumber: 'CTRI/2023/04/052180',
    ctriStatus: 'Registered',
    iecName: 'AIIA Institutional Ethics Committee',
    iecApprovalRef: 'AIIA/IEC/2023/021',
    iecApprovalDate: '2023-03-20',
    iecExpiryDate: '2025-03-19',
    iecStatus: 'Approved',
    documentsCount: 26,
    budgetAllocatedLakhs: 41.5,
    createdAt: '2023-02-01T10:00:00Z',
    updatedAt: '2026-01-10T16:00:00Z',
    assignedTeam: [
      { userId: 'user-pi-01', name: 'Dr. Sujata Sharma', role: 'pi' },
      { userId: 'user-pv-01', name: 'Dr. Priya Nair', role: 'pharmacovigilance_officer' }
    ],
    milestones: [
      { id: 'm-1001', title: 'Study Close-out Visit and Clinical Study Report Sign-off', category: 'reporting', plannedDate: '2025-12-15', actualDate: '2025-12-10', responsiblePerson: 'Dr. Sujata Sharma', status: 'completed' }
    ]
  }
];

// Generate 260 Synthetic Participants with realistic distributions
export const MOCK_PARTICIPANTS: Participant[] = [];
const firstNames = ['Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun', 'Sai', 'Reyansh', 'Ayaan', 'Krishna', 'Ishaan', 'Diya', 'Saanvi', 'Aanya', 'Aadhya', 'Ananya', 'Pari', 'Anika', 'Navya', 'Myra', 'Ira', 'Meera', 'Rohan', 'Kavya', 'Tarun', 'Pooja'];
const lastNames = ['Sharma', 'Verma', 'Patel', 'Deshmukh', 'Iyer', 'Nair', 'Singh', 'Gupta', 'Reddy', 'Banerjee', 'Chaudhary', 'Mishra', 'Joshi', 'Bhatt', 'Rao', 'Pillai', 'Kulkarni'];

let participantCounter = 1;
const studyDistribution = [
  { studyId: 'study-001', studyCode: 'AIIA-CT-2024-001', count: 65, siteId: 'site-01', siteCode: 'AIIA-DEL' },
  { studyId: 'study-001', studyCode: 'AIIA-CT-2024-001', count: 45, siteId: 'site-02', siteCode: 'IPGTRA-JAM' },
  { studyId: 'study-001', studyCode: 'AIIA-CT-2024-001', count: 40, siteId: 'site-03', siteCode: 'NIA-JAI' },
  { studyId: 'study-002', studyCode: 'AIIA-CT-2024-002', count: 50, siteId: 'site-01', siteCode: 'AIIA-DEL' },
  { studyId: 'study-003', studyCode: 'AIIA-CT-2024-003', count: 35, siteId: 'site-01', siteCode: 'AIIA-DEL' },
  { studyId: 'study-004', studyCode: 'AIIA-CT-2025-004', count: 25, siteId: 'site-03', siteCode: 'NIA-JAI' }
];

for (const dist of studyDistribution) {
  for (let i = 0; i < dist.count; i++) {
    const idNum = participantCounter++;
    const syntheticId = `DEMO-${String(idNum).padStart(4, '0')}`;
    const age = 22 + (idNum * 7) % 52;
    const gender = idNum % 2 === 0 ? 'Female' : 'Male';
    const isScreenFailure = idNum % 14 === 0;
    const isCompleted = idNum % 4 === 0 && !isScreenFailure;
    const isWithdrawn = idNum % 23 === 0 && !isScreenFailure;
    
    let currentStatus: Participant['currentStatus'] = 'Active Treatment';
    let eligibilityStatus: Participant['eligibilityStatus'] = 'Eligible';
    let consentStatus: Participant['consentStatus'] = 'Consented';
    let enrolmentStatus: Participant['enrolmentStatus'] = 'Enrolled';
    let screenFailureReason: string | undefined = undefined;

    if (isScreenFailure) {
      currentStatus = 'Screen Failure';
      eligibilityStatus = 'Screen Failure';
      enrolmentStatus = 'Not Enrolled';
      screenFailureReason = idNum % 2 === 0 
        ? 'Inclusion: Baseline HAM-A Score < 18 on clinical assessment'
        : 'Exclusion: Concurrent systemic corticosteroid therapy in past 30 days';
    } else if (isWithdrawn) {
      currentStatus = 'Withdrawn';
      enrolmentStatus = 'Enrolled';
    } else if (isCompleted) {
      currentStatus = 'Completed';
      enrolmentStatus = 'Enrolled';
    }

    const completedVisits = isCompleted ? 6 : isScreenFailure ? 1 : Math.min(5, (idNum % 5) + 1);
    const adherence = isScreenFailure ? 0 : 78 + (idNum * 3) % 22;
    const hasAdverseEvent = idNum % 11 === 0 && !isScreenFailure;

    MOCK_PARTICIPANTS.push({
      id: `part-${idNum}`,
      syntheticId,
      studyId: dist.studyId,
      studyCode: dist.studyCode,
      siteId: dist.siteId,
      siteCode: dist.siteCode,
      age,
      gender,
      screeningNumber: `SCR-${dist.siteCode}-${String(100 + idNum)}`,
      screeningDate: `2024-${String(1 + (idNum % 12)).padStart(2, '0')}-15`,
      eligibilityStatus,
      screenFailureReason,
      consentStatus,
      consentDate: `2024-${String(1 + (idNum % 12)).padStart(2, '0')}-14`,
      enrolmentStatus,
      enrolmentDate: isScreenFailure ? undefined : `2024-${String(1 + (idNum % 12)).padStart(2, '0')}-18`,
      randomizationId: isScreenFailure ? undefined : `RND-${dist.siteCode}-${String(500 + idNum)}`,
      treatmentArm: idNum % 2 === 0 ? 'Experimental (ASU Formulation)' : 'Active Comparator',
      currentStatus,
      adherencePercentage: adherence,
      completedVisitsCount: completedVisits,
      totalScheduledVisits: 6,
      hasAdverseEvent,
      notes: hasAdverseEvent ? 'Safety case report filed under PV-2026 series' : undefined
    });
  }
}

// 18 Pharmacovigilance Safety Cases (Core Differentiator for AIIA & NPvCC)
export const MOCK_SAFETY_CASES: SafetyCase[] = [
  {
    id: 'case-pv-001',
    caseNumber: 'NPVCC/2026/SAE-001',
    studyId: 'study-001',
    studyCode: 'AIIA-CT-2024-001',
    siteId: 'site-01',
    siteName: 'AIIA Apex Hospital, New Delhi',
    syntheticParticipantId: 'DEMO-0011',
    reportType: 'Initial',
    receivedDate: '2026-09-27T08:30:00Z',
    reporterName: 'Dr. Sujata Sharma',
    reporterRole: 'Principal Investigator',
    eventTerm: 'Acute Urticaria with Facial Angioedema',
    meddraSyntheticCode: 'MEDDRA-SYN-10046532',
    ayushTermEquivalent: 'Sheetapitta / Kotha with Shotha',
    eventOnsetDate: '2026-09-26',
    outcome: 'Recovering / Resolving',
    isSerious: true,
    seriousnessCriteria: ['hospitalization', 'medically_significant'],
    severity: 'Severe',
    expectedness: 'Unexpected',
    suspectedProduct: 'Standardized Ashwagandha Aqueous Extract 300mg',
    ayushDosageForm: 'Capsule',
    batchNumber: 'ASH-LOT-24-098B',
    dosageAndRoute: '1 capsule (300mg) twice daily orally with water',
    therapyStartDate: '2026-09-12',
    therapyStopDate: '2026-09-26',
    dechallenge: 'Positive (improved upon stopping)',
    rechallenge: 'Not Done',
    concomitantMedications: 'None documented',
    causalityAssessment: 'Probable / Likely',
    naranjoScore: 6,
    medicalSummary: 'Participant developed generalized pruritic wheals and bilateral periorbital edema within 14 days of starting investigational Ashwagandha batch. Admitted to emergency observation unit; received intramuscular hydrocortisone and oral cetirizine. Symptoms resolved over 24 hours. Suspected idiosyncratic hypersensitivity to excipient or Withanolide fraction.',
    assessedBy: 'Dr. Priya Nair (Pharmacovigilance Officer)',
    assessedDate: '2026-09-27T14:00:00Z',
    dsmbReviewStatus: 'Pending DSMB',
    regulatoryDeadlineHours: 24, // Serious unexpected ADR requiring 24h notification
    deadlineDate: '2026-09-28T08:30:00Z', // Critical: approaching now
    submissionStatus: 'Submitted to NPvCC',
    submissionDate: '2026-09-27T16:00:00Z',
    ackReference: 'NPVCC-ACK-2026-0982',
    overdue: false
  },
  {
    id: 'case-pv-002',
    caseNumber: 'NPVCC/2026/SAE-002',
    studyId: 'study-003',
    studyCode: 'AIIA-CT-2024-003',
    siteId: 'site-06',
    siteName: 'R.A. Podar Medical College, Mumbai',
    syntheticParticipantId: 'DEMO-0022',
    reportType: 'Follow-up 1',
    receivedDate: '2026-09-20T11:00:00Z',
    reporterName: 'Dr. Sampada Sant',
    reporterRole: 'Site Principal Investigator',
    eventTerm: 'Upper Gastrointestinal Bleeding with Melena',
    meddraSyntheticCode: 'MEDDRA-SYN-10018898',
    ayushTermEquivalent: 'Urdhwaga Raktapitta',
    eventOnsetDate: '2026-09-18',
    outcome: 'Recovered / Resolved',
    isSerious: true,
    seriousnessCriteria: ['hospitalization', 'life_threatening'],
    severity: 'Severe',
    expectedness: 'Expected',
    suspectedProduct: 'Aceclofenac 100mg bid (Comparator Arm)',
    ayushDosageForm: 'Tablet',
    batchNumber: 'CMP-ACE-2025-11',
    dosageAndRoute: '100mg twice daily with meals',
    therapyStartDate: '2026-08-01',
    therapyStopDate: '2026-09-18',
    dechallenge: 'Positive (improved upon stopping)',
    rechallenge: 'Not Done',
    concomitantMedications: 'Rabeprazole 20mg od',
    causalityAssessment: 'Certain',
    naranjoScore: 8,
    medicalSummary: 'Elderly female participant randomized to NSAID comparator arm experienced acute erosive gastritis and hematemesis. Required hospital admission and endoscopic hemostasis. Investigational Nano-Curcumin arm demonstrated zero GI bleeds to date.',
    assessedBy: 'Dr. Priya Nair',
    assessedDate: '2026-09-21T10:00:00Z',
    dsmbReviewStatus: 'DSMB Concurrence',
    regulatoryDeadlineHours: 24,
    deadlineDate: '2026-09-21T11:00:00Z',
    submissionStatus: 'Forwarded to CDSCO',
    submissionDate: '2026-09-21T09:30:00Z',
    ackReference: 'CDSCO-CT-ACK-2026-4412',
    overdue: false
  },
  {
    id: 'case-pv-003',
    caseNumber: 'NPVCC/2026/ADR-003',
    studyId: 'study-004',
    studyCode: 'AIIA-CT-2025-004',
    siteId: 'site-03',
    siteName: 'National Institute of Ayurveda, Jaipur',
    syntheticParticipantId: 'DEMO-0033',
    reportType: 'Initial',
    receivedDate: '2026-09-15T09:00:00Z',
    reporterName: 'Prof. Sanjeev Sharma',
    reporterRole: 'Co-Investigator',
    eventTerm: 'Mild Hypoglycemic Symptoms (Tremor and Diaphoresis)',
    meddraSyntheticCode: 'MEDDRA-SYN-10020993',
    ayushTermEquivalent: 'Kshudha-adhikya / Sveda-pravritti',
    eventOnsetDate: '2026-09-14',
    outcome: 'Recovered / Resolved',
    isSerious: false,
    seriousnessCriteria: [],
    severity: 'Mild',
    expectedness: 'Expected',
    suspectedProduct: 'Guduchi Ghanvati 1g bid with Amalaki Churna',
    ayushDosageForm: 'Vati / Gutika (Tablet)',
    batchNumber: 'GUD-AM-2025-04',
    dosageAndRoute: '1g morning and evening postprandial',
    therapyStartDate: '2026-08-20',
    therapyStopDate: '2026-09-14',
    dechallenge: 'Positive (improved upon stopping)',
    rechallenge: 'Positive (recurred)',
    concomitantMedications: 'Metformin 500mg od (Synergistic glycemic lowering observed)',
    causalityAssessment: 'Probable / Likely',
    naranjoScore: 7,
    medicalSummary: 'Synergistic hypoglycemic potentiating effect of Guduchi when combined with Metformin in borderline diabetic patient. Metformin dose adjusted from 500mg to 250mg; Guduchi continued safely without further events.',
    assessedBy: 'Dr. Priya Nair',
    assessedDate: '2026-09-16T15:00:00Z',
    dsmbReviewStatus: 'Not Required',
    regulatoryDeadlineHours: 336, // 14-day standard reporting window
    deadlineDate: '2026-09-29T09:00:00Z',
    submissionStatus: 'Submitted to NPvCC',
    submissionDate: '2026-09-16T16:00:00Z',
    ackReference: 'NPVCC-ACK-2026-1014',
    overdue: false
  },
  {
    id: 'case-pv-004',
    caseNumber: 'NPVCC/2026/ADR-004',
    studyId: 'study-002',
    studyCode: 'AIIA-CT-2024-002',
    siteId: 'site-01',
    siteName: 'AIIA Apex Hospital, New Delhi',
    syntheticParticipantId: 'DEMO-0044',
    reportType: 'Initial',
    receivedDate: '2026-09-10T14:00:00Z',
    reporterName: 'Rajesh Kumar',
    reporterRole: 'Study Coordinator',
    eventTerm: 'Bitter Taste Dysgeusia & Transient Epigastric Burning',
    meddraSyntheticCode: 'MEDDRA-SYN-10013911',
    ayushTermEquivalent: 'Tikta Asyasyata & Amlapitta',
    eventOnsetDate: '2026-09-08',
    outcome: 'Recovered / Resolved',
    isSerious: false,
    seriousnessCriteria: [],
    severity: 'Mild',
    expectedness: 'Expected',
    suspectedProduct: 'AYUSH-64 Tablet (500mg)',
    ayushDosageForm: 'Vati / Gutika (Tablet)',
    batchNumber: 'A64-DEL-24-01',
    dosageAndRoute: '2 tablets tid with lukewarm water after food',
    therapyStartDate: '2026-09-07',
    dechallenge: 'Positive (improved upon stopping)',
    rechallenge: 'Not Done',
    concomitantMedications: 'Paracetamol 650mg SOS',
    causalityAssessment: 'Certain',
    naranjoScore: 8,
    medicalSummary: 'Known pharmacodynamic attribute of Chirayata (Swertia chirata) and Katuki in AYUSH-64 formulation. Mitigated by advising lukewarm water with teaspoon of honey as anupana.',
    assessedBy: 'Dr. Priya Nair',
    assessedDate: '2026-09-12T11:00:00Z',
    dsmbReviewStatus: 'Not Required',
    regulatoryDeadlineHours: 336,
    deadlineDate: '2026-09-24T14:00:00Z',
    submissionStatus: 'Submitted to NPvCC',
    submissionDate: '2026-09-12T14:00:00Z',
    ackReference: 'NPVCC-ACK-2026-0891',
    overdue: false
  },
  {
    id: 'case-pv-005',
    caseNumber: 'NPVCC/2026/SAE-005',
    studyId: 'study-006',
    studyCode: 'AIIA-CT-2025-006',
    siteId: 'site-06',
    siteName: 'R.A. Podar Medical College, Mumbai',
    syntheticParticipantId: 'DEMO-0055',
    reportType: 'Initial',
    receivedDate: '2026-08-25T16:00:00Z',
    reporterName: 'Dr. Sampada Sant',
    reporterRole: 'Site Principal Investigator',
    eventTerm: 'Elevated Serum Creatinine (1.8 mg/dL) with Oliguria',
    meddraSyntheticCode: 'MEDDRA-SYN-10005483',
    ayushTermEquivalent: 'Mutraghata / Mutrakrichhra',
    eventOnsetDate: '2026-08-24',
    outcome: 'Recovered / Resolved',
    isSerious: true,
    seriousnessCriteria: ['hospitalization', 'medically_significant'],
    severity: 'Moderate',
    expectedness: 'Unexpected',
    suspectedProduct: 'Punarnavadi Mandura 500mg bid',
    ayushDosageForm: 'Vati / Gutika (Tablet)',
    batchNumber: 'PUN-LOT-25-03',
    dosageAndRoute: '1 tablet bid with butter-milk',
    therapyStartDate: '2026-07-20',
    therapyStopDate: '2026-08-24',
    dechallenge: 'Positive (improved upon stopping)',
    rechallenge: 'Not Done',
    concomitantMedications: 'Calcium carbonate 500mg od',
    causalityAssessment: 'Unlikely',
    naranjoScore: 2,
    medicalSummary: 'Participant had pre-existing severe dehydration following acute gastroenteritis episode 48 hours prior. Rehydration corrected creatinine back to baseline (0.9 mg/dL). Heavy metal test on batch confirmed Lead, Arsenic, Cadmium well within Ayurvedic Pharmacopoeia of India (API) limits.',
    assessedBy: 'Dr. Priya Nair',
    assessedDate: '2026-08-26T14:00:00Z',
    dsmbReviewStatus: 'DSMB Concurrence',
    regulatoryDeadlineHours: 24,
    deadlineDate: '2026-08-26T16:00:00Z',
    submissionStatus: 'Forwarded to CDSCO',
    submissionDate: '2026-08-26T12:00:00Z',
    ackReference: 'CDSCO-ACK-2026-7782',
    overdue: false
  },
  {
    id: 'case-pv-006',
    caseNumber: 'NPVCC/2026/SAE-006',
    studyId: 'study-008',
    studyCode: 'AIIA-CT-2026-008',
    siteId: 'site-02',
    siteName: 'ITRA / IPGTRA, Jamnagar',
    syntheticParticipantId: 'DEMO-0066',
    reportType: 'Initial',
    receivedDate: '2026-09-22T10:00:00Z',
    reporterName: 'Prof. Mahesh Vyas',
    reporterRole: 'Site Investigator',
    eventTerm: 'Transient Maculopapular Exanthema post Rasasindura',
    meddraSyntheticCode: 'MEDDRA-SYN-10015533',
    ayushTermEquivalent: 'Rasa-dravya Kotha',
    eventOnsetDate: '2026-09-21',
    outcome: 'Recovering / Resolving',
    isSerious: false,
    seriousnessCriteria: [],
    severity: 'Moderate',
    expectedness: 'Expected',
    suspectedProduct: 'Rasasindura 60mg od with Honey',
    ayushDosageForm: 'Kupipakwa Rasayana (Sublimated Formulation)',
    batchNumber: 'RS-ITRA-26-01',
    dosageAndRoute: '60mg single daily dose with pure honey',
    therapyStartDate: '2026-09-15',
    therapyStopDate: '2026-09-21',
    dechallenge: 'Positive (improved upon stopping)',
    rechallenge: 'Not Done',
    concomitantMedications: 'None',
    causalityAssessment: 'Possible',
    naranjoScore: 5,
    medicalSummary: 'Kupipakwa mercury sulfide formulation monitored under national safety registry. Pruritic rash spontaneously subsided after drug cessation and administration of Sarivadyasava.',
    assessedBy: 'Dr. Priya Nair',
    assessedDate: '2026-09-23T16:00:00Z',
    dsmbReviewStatus: 'Pending DSMB',
    regulatoryDeadlineHours: 168, // 7 days expedited
    deadlineDate: '2026-09-29T10:00:00Z',
    submissionStatus: 'Submitted to NPvCC',
    submissionDate: '2026-09-24T09:30:00Z',
    ackReference: 'NPVCC-ACK-2026-1088',
    overdue: false
  }
];

// Monitoring Visits & Findings
export const MOCK_MONITORING_VISITS: MonitoringVisit[] = [
  {
    id: 'mon-001',
    visitNumber: 'MON-2026-01',
    studyId: 'study-001',
    siteId: 'site-01',
    monitorName: 'Ananya Deshmukh',
    visitType: 'Interim Monitoring (IMV)',
    scheduledDate: '2026-08-15',
    conductedDate: '2026-08-15',
    status: 'completed',
    summaryFindings: 'Reviewed 25 participant binders. Found 2 minor consent date transcription errors and 1 study medication storage temperature log gap.',
    totalFindings: 3,
    openFindings: 1,
    capaRequired: true
  },
  {
    id: 'mon-002',
    visitNumber: 'MON-2026-02',
    studyId: 'study-001',
    siteId: 'site-02',
    monitorName: 'Ananya Deshmukh',
    visitType: 'Interim Monitoring (IMV)',
    scheduledDate: '2026-07-28',
    conductedDate: '2026-07-28',
    status: 'completed',
    summaryFindings: 'Excellent source data verification adherence. 1 IP dispensing count discrepancy noted during batch reconciliations.',
    totalFindings: 2,
    openFindings: 1,
    capaRequired: true
  },
  {
    id: 'mon-003',
    visitNumber: 'MON-2026-03',
    studyId: 'study-003',
    siteId: 'site-06',
    monitorName: 'Ananya Deshmukh',
    visitType: 'For-Cause Audit',
    scheduledDate: '2026-05-18',
    conductedDate: '2026-05-18',
    status: 'completed',
    summaryFindings: 'Ethics committee renewal was not processed on time before protocol amendment v1.4 implementation.',
    totalFindings: 5,
    openFindings: 3,
    capaRequired: true
  },
  {
    id: 'mon-004',
    visitNumber: 'MON-2026-04',
    studyId: 'study-002',
    siteId: 'site-04',
    monitorName: 'Ananya Deshmukh',
    visitType: 'Interim Monitoring (IMV)',
    scheduledDate: '2026-09-20',
    status: 'overdue',
    summaryFindings: 'Site visit postponed due to investigator travel; rescheduled for immediate execution.',
    totalFindings: 4,
    openFindings: 4,
    capaRequired: true
  }
];

export const MOCK_MONITORING_FINDINGS: MonitoringFinding[] = [
  {
    id: 'find-001',
    monitoringVisitId: 'mon-001',
    studyId: 'study-001',
    siteId: 'site-01',
    category: 'Consent & Regulatory',
    severity: 'Minor',
    description: 'Participant DEMO-0014 consent form had date written by CRC rather than participant himself.',
    rootCause: 'CRC assisted elderly participant without formal impartial witness documentation.',
    capaAction: 'Re-consent obtained with impartial family witness; CRC team retrained on GCP-ASU section 3.2.',
    responsiblePerson: 'Rajesh Kumar',
    dueDate: '2026-09-01',
    status: 'Resolved',
    resolutionNotes: 'Verified re-consent document in on-site binder on 2026-09-01.',
    resolvedAt: '2026-09-01'
  },
  {
    id: 'find-002',
    monitoringVisitId: 'mon-001',
    studyId: 'study-001',
    siteId: 'site-01',
    category: 'IP Accountability',
    severity: 'Major',
    description: 'Temperature data logger in Ayurveda Pharmacy drug dispensary room uncalibrated for 45 days.',
    rootCause: 'Annual vendor calibration contract expired without alert notification.',
    capaAction: 'Calibrated NIST-traceable digital logger installed; temperature deviation logs reviewed; drug efficacy unaffected as room was climate-controlled at 22C.',
    responsiblePerson: 'Dr. Sujata Sharma',
    dueDate: '2026-09-30',
    status: 'In Progress'
  },
  {
    id: 'find-003',
    monitoringVisitId: 'mon-003',
    studyId: 'study-003',
    siteId: 'site-06',
    category: 'Consent & Regulatory',
    severity: 'Critical',
    description: 'Site ethics committee continuing review expired on 2026-07-14. 8 participants enrolled without active renewal.',
    rootCause: 'Site administrative backlog in submission of annual progress report to local IEC.',
    capaAction: 'Enrolment temporarily paused at Site 06; urgent expedited continuing review dossier submitted to IEC Chair.',
    responsiblePerson: 'Dr. Sampada Sant',
    dueDate: '2026-10-02',
    status: 'Open'
  }
];

// Protocol Deviations
export const MOCK_DEVIATIONS: ProtocolDeviation[] = [
  {
    id: 'dev-001',
    deviationCode: 'DEV-2026-001',
    studyId: 'study-001',
    siteId: 'site-01',
    participantId: 'DEMO-0018',
    dateIdentified: '2026-09-14',
    category: 'Visit Window Exceeded',
    severity: 'Minor',
    description: 'Participant attended Week 8 follow-up visit 9 days past the +/- 3 days allowable protocol window.',
    impactAssessment: 'Minimal impact on overall primary efficacy outcome; visit vitals and HAM-A scale recorded accurately.',
    rootCause: 'Participant experienced festival travel and could not report to clinic on planned date.',
    correctiveAction: 'Telephone reminder schedule updated with 5-day advance SMS alert.',
    preventiveAction: 'Automated WhatsApp/SMS visit reminder system activated for all active participants.',
    responsiblePerson: 'Rajesh Kumar',
    dueDate: '2026-09-25',
    reportedToIEC: false,
    status: 'Closed'
  },
  {
    id: 'dev-002',
    deviationCode: 'DEV-2026-002',
    studyId: 'study-003',
    siteId: 'site-06',
    participantId: 'DEMO-0024',
    dateIdentified: '2026-09-02',
    category: 'Prohibited Concomitant Med',
    severity: 'Major',
    description: 'Participant in Haridra Nano-extract arm self-administered high-dose Ibuprofen 400mg for 4 days for dental pain.',
    impactAssessment: 'Potential confounding of primary knee pain WOMAC visual analog score at Week 4 assessment.',
    rootCause: 'Participant did not notify dental surgeon regarding ongoing double-blind RCT participation.',
    correctiveAction: 'Wallet participant card issued clearly detailing clinical trial enrollment and prohibited medications.',
    preventiveAction: 'Study coordinator revised dispensing counseling protocol to emphasize reporting any new prescription.',
    responsiblePerson: 'Dr. Sampada Sant',
    dueDate: '2026-09-30',
    reportedToIEC: true,
    iecNotificationDate: '2026-09-05',
    status: 'CAPA Implemented'
  },
  {
    id: 'dev-003',
    deviationCode: 'DEV-2026-003',
    studyId: 'study-002',
    siteId: 'site-04',
    dateIdentified: '2026-08-20',
    category: 'IP Dosing / Non-compliance',
    severity: 'Major',
    description: 'Site dispensing nurse mistakenly provided AYUSH-64 batch expiring in Sept 2026 instead of newly replenished Lot 2027.',
    impactAssessment: 'Medication was fully within valid shelf-life; no sub-potency or patient harm.',
    rootCause: 'FIFO (First-In, First-Out) shelf storage layout was disrupted during routine pharmacy cleaning.',
    correctiveAction: 'Quarantine and designated shelf color-coding instituted in site IP locker.',
    preventiveAction: 'Mandatory two-person double-check on e-Dispense barcode scanning.',
    responsiblePerson: 'Dr. Anand Kumar Chaudhary',
    dueDate: '2026-09-15',
    reportedToIEC: true,
    iecNotificationDate: '2026-08-25',
    status: 'Closed'
  }
];

// Data Queries
export const MOCK_DATA_QUERIES: DataQuery[] = [
  {
    id: 'dq-001',
    queryNumber: 'DQ-2026-0101',
    studyId: 'study-001',
    siteId: 'site-01',
    participantId: 'DEMO-0005',
    formName: 'Vital Signs & Prakriti Assessment',
    fieldName: 'Diastolic Blood Pressure',
    queryText: 'Recorded DBP is 128 mmHg with SBP 132 mmHg. Please verify if value was meant to be 82 mmHg.',
    raisedBy: 'Ananya Deshmukh (CRA)',
    raisedDate: '2026-09-20',
    assignedRole: 'study_coordinator',
    status: 'Answered',
    responseNotes: 'Confirmed clerical transposition error in electronic CRF. Source clinical chart shows 82 mmHg. Corrected in eCRF.',
    closedDate: '2026-09-22'
  },
  {
    id: 'dq-002',
    queryNumber: 'DQ-2026-0102',
    studyId: 'study-002',
    siteId: 'site-04',
    participantId: 'DEMO-0048',
    formName: 'End of Treatment Summary',
    fieldName: 'Study Drug Return Count',
    queryText: 'Dispensed 84 tablets; returned 0 tablets, but compliance logged as 70%. Please clarify discrepancy.',
    raisedBy: 'Ananya Deshmukh (CRA)',
    raisedDate: '2026-09-24',
    assignedRole: 'study_coordinator',
    status: 'Open'
  },
  {
    id: 'dq-003',
    queryNumber: 'DQ-2026-0103',
    studyId: 'study-001',
    siteId: 'site-02',
    participantId: 'DEMO-0019',
    formName: 'Inclusion / Exclusion Checklist',
    fieldName: 'ECG QTc Interval',
    queryText: 'Baseline ECG QTc value missing from Day 0 screening form.',
    raisedBy: 'Dr. Priya Nair (NPvCC)',
    raisedDate: '2026-09-25',
    assignedRole: 'pi',
    status: 'Open'
  }
];

// Ethics Submissions
export const MOCK_ETHICS: EthicsSubmission[] = [
  {
    id: 'eth-001',
    studyId: 'study-001',
    studyCode: 'AIIA-CT-2024-001',
    iecName: 'AIIA Institutional Ethics Committee for Human Research',
    submissionRef: 'AIIA/IEC/2024/PROT-089',
    protocolVersion: 'v3.2',
    submissionDate: '2024-03-01',
    reviewMeetingDate: '2024-04-05',
    approvalStatus: 'Approved',
    approvalRef: 'AIIA/IEC/APPROVAL/2024/089',
    approvalDate: '2024-04-12',
    expiryDate: '2027-04-11',
    isNearingExpiry: false,
    continuingReviewDueDate: '2027-02-15',
    requiredDocumentsChecklist: [
      { docName: 'Investigator Brochure (IB) v3.0', submitted: true, approved: true },
      { docName: 'Patient Information Sheet (Hindi & English)', submitted: true, approved: true },
      { docName: 'Informed Consent Form (ICMR Format)', submitted: true, approved: true },
      { docName: 'Clinical Trial Agreement & Insurance Policy', submitted: true, approved: true },
      { docName: 'GMP & CoA Certificates of Ashwagandha Extract', submitted: true, approved: true }
    ]
  },
  {
    id: 'eth-002',
    studyId: 'study-002',
    studyCode: 'AIIA-CT-2024-002',
    iecName: 'Central Ethics Committee, AIIA',
    submissionRef: 'AIIA/CEC/2024/044',
    protocolVersion: 'v2.1',
    submissionDate: '2024-01-05',
    reviewMeetingDate: '2024-01-18',
    approvalStatus: 'Approved',
    approvalRef: 'AIIA/CEC/2024/044',
    approvalDate: '2024-01-20',
    expiryDate: '2026-10-25',
    isNearingExpiry: true, // Urgent: expires in ~27 days
    continuingReviewDueDate: '2026-09-30',
    requiredDocumentsChecklist: [
      { docName: 'Annual Progress & Safety Report 2026', submitted: true, approved: false },
      { docName: 'Updated Investigator List', submitted: true, approved: true }
    ]
  },
  {
    id: 'eth-003',
    studyId: 'study-007',
    studyCode: 'AIIA-CT-2026-007',
    iecName: 'AIIA Institutional Ethics Committee',
    submissionRef: 'AIIA/IEC/SUB-2026-014',
    protocolVersion: 'v1.0',
    submissionDate: '2026-08-10',
    reviewMeetingDate: '2026-10-05',
    approvalStatus: 'Under Review',
    approvalRef: 'Pending',
    approvalDate: '',
    expiryDate: '',
    isNearingExpiry: false,
    continuingReviewDueDate: '',
    requiredDocumentsChecklist: [
      { docName: 'Protocol v1.0 & Statistical Plan', submitted: true, approved: false },
      { docName: 'Vernacular Audio-Visual Consent Script', submitted: true, approved: false }
    ]
  }
];

// Cryptographic ALCOA+ Audit Trail Initial Ledger
const baseAuditEntries = [
  {
    seq: 1,
    actorId: 'user-admin-01',
    actorName: 'Vikramaditya Sen',
    actorRole: 'admin' as const,
    action: 'CREATE' as const,
    recordType: 'Study' as const,
    recordId: 'study-001',
    recordIdentifier: 'AIIA-CT-2024-001',
    timestamp: '2024-02-15T10:00:00Z',
    details: 'Initial study registration entered into AIIA CTMS system with planned target 240 subjects.',
    ipAddress: '14.139.58.12'
  },
  {
    seq: 2,
    actorId: 'user-iec-01',
    actorName: 'Prof. V. K. Joshi',
    actorRole: 'iec_member' as const,
    action: 'APPROVE' as const,
    recordType: 'Study' as const,
    recordId: 'study-001',
    recordIdentifier: 'AIIA/IEC/2024/PROT-089',
    timestamp: '2024-04-12T16:30:00Z',
    details: 'Full committee ethics approval issued under CDSCO registration ECR/123/Inst/DL/2013/RR-19.',
    ipAddress: '14.139.58.25'
  },
  {
    seq: 3,
    actorId: 'user-coord-01',
    actorName: 'Rajesh Kumar',
    actorRole: 'study_coordinator' as const,
    action: 'CREATE' as const,
    recordType: 'Participant' as const,
    recordId: 'part-1',
    recordIdentifier: 'DEMO-0001',
    timestamp: '2024-06-02T09:15:00Z',
    details: 'Screening and informed consent recorded for first subject in Ashwagandha trial.',
    ipAddress: '14.139.58.44'
  },
  {
    seq: 4,
    actorId: 'user-pv-01',
    actorName: 'Dr. Priya Nair',
    actorRole: 'pharmacovigilance_officer' as const,
    action: 'SAFETY_SUBMIT' as const,
    recordType: 'SafetyCase' as const,
    recordId: 'case-pv-001',
    recordIdentifier: 'NPVCC/2026/SAE-001',
    timestamp: '2026-09-27T16:00:00Z',
    details: 'Serious Adverse Event (Acute Angioedema) reported within 24-hr regulatory window to NPvCC coordinating center.',
    ipAddress: '14.139.58.89'
  },
  {
    seq: 5,
    actorId: 'user-cra-01',
    actorName: 'Ananya Deshmukh',
    actorRole: 'cra_monitor' as const,
    action: 'UPDATE' as const,
    recordType: 'Monitoring' as const,
    recordId: 'mon-001',
    recordIdentifier: 'MON-2026-01',
    timestamp: '2026-08-16T11:20:00Z',
    details: 'Monitoring visit report finalized; 3 findings issued with corrective action milestones.',
    ipAddress: '103.21.124.9'
  }
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [];
let prevHash = '0000000000000000000000000000000000000000000000000000000000000000';

for (const entry of baseAuditEntries) {
  const hashPayload = `${prevHash}|${entry.seq}|${entry.timestamp}|${entry.actorId}|${entry.action}|${entry.recordType}|${entry.recordId}|${entry.details}`;
  const currentHash = syncComputeSimpleHash(hashPayload);
  
  MOCK_AUDIT_LOGS.push({
    id: `audit-${entry.seq}`,
    sequenceNumber: entry.seq,
    actorId: entry.actorId,
    actorName: entry.actorName,
    actorRole: entry.actorRole,
    action: entry.action,
    recordType: entry.recordType,
    recordId: entry.recordId,
    recordIdentifier: entry.recordIdentifier,
    timestamp: entry.timestamp,
    details: entry.details,
    ipAddress: entry.ipAddress,
    previousHash: prevHash,
    currentHash
  });
  
  prevHash = currentHash;
}

// Notifications
export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-001',
    category: 'safety',
    title: 'Urgent SAE Triage: 24h Deadline Approaching',
    message: 'Safety Case NPVCC/2026/SAE-001 (DEMO-0011, Angioedema) requires final DSMB acknowledgment before 28-Sep 08:30 IST.',
    priority: 'critical',
    actionUrl: '/pharmacovigilance/case-pv-001',
    isRead: false,
    createdAt: '2026-09-28T06:00:00Z',
    responsibleRole: 'pharmacovigilance_officer'
  },
  {
    id: 'notif-002',
    category: 'ethics',
    title: 'IEC Approval Expiry Warning (27 Days Remaining)',
    message: 'Study AIIA-CT-2024-002 (AYUSH-64) IEC approval expires on 25-Oct-2026. Annual continuing review report is overdue.',
    priority: 'high',
    actionUrl: '/ethics',
    isRead: false,
    createdAt: '2026-09-27T09:00:00Z',
    responsibleRole: 'pi'
  },
  {
    id: 'notif-003',
    category: 'monitoring',
    title: 'Site 04 Monitoring Visit Overdue',
    message: 'Scheduled monitoring visit MON-2026-04 at IMS BHU Varanasi was due on 20-Sep-2026.',
    priority: 'medium',
    actionUrl: '/monitoring',
    isRead: false,
    createdAt: '2026-09-25T14:30:00Z',
    responsibleRole: 'cra_monitor'
  },
  {
    id: 'notif-004',
    category: 'deviation',
    title: 'Open Critical Protocol Deviation',
    message: 'DEV-2026-002 (Prohibited Concomitant Medication) CAPA due on 30-Sep-2026.',
    priority: 'high',
    actionUrl: '/deviations',
    isRead: false,
    createdAt: '2026-09-24T11:00:00Z',
    responsibleRole: 'cra_monitor'
  },
  {
    id: 'notif-005',
    category: 'recruitment',
    title: 'Study 001 Reached 90% Target Enrolment',
    message: 'Ashwagandha Anxiety RCT has successfully enrolled 218 out of 240 planned participants.',
    priority: 'low',
    actionUrl: '/studies/study-001',
    isRead: true,
    createdAt: '2026-09-20T10:00:00Z',
    responsibleRole: 'pi'
  }
];
